[workspace]
members = ["projects/*"]
default-members = [
    "projects/deep-danbooru",
]
exclude = [
    "projects/.DS_Store",
    "projects/deep-danbooru-models",
]

[profile.release]
lto = true
panic = "abort"
